# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'AFNetworking', '~> 3.0'

  # Pods for Runner

end
